[alias]
swift = ["bin", "cargo-swift"]
xcode = ["bin", "cargo-xcode"]

[target.x86_64-apple-ios]
rustflags = [
    "-C", "link-arg=-isysroot",
    "-C", "link-arg=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk",
    "-C", "link-arg=-L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib",
    "-C", "link-arg=-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks",
]
linker = "/usr/bin/clang"

[target.aarch64-apple-ios]
rustflags = [
    "-C", "link-arg=-isysroot",
    "-C", "link-arg=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk",
    "-C", "link-arg=-L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib",
    "-C", "link-arg=-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks",
]
linker = "/usr/bin/clang"

[target.aarch64-apple-ios-sim]
linker = "/usr/bin/clang"

